id = "nano"
name = "Nano"
version = "0.0.1"
schema_version = 1
authors = ["Pedro Braga <mrhenribraga@gmail.com>"]
description = "nano support."
repository = "https://github.com/mrpedrobraga/zed-nano"

[language_servers.nnls]
name = "NNLS"
language = "nano"

[grammars.nano]
repository = "https://github.com/mrpedrobraga/tree-sitter-nano"
commit = "9f1772961500fd7845864f04b9e8a5f71a047f7a"
