id = "nano"
name = "Nano"
version = "0.0.1"
schema_version = 1
authors = ["Pedro Braga <mrhenribraga@gmail.com>"]
description = "nano support."
repository = "https://github.com/mrpedrobraga/zed-nano"

[grammars.nano]
repository = "https://github.com/mrpedrobraga/tree-sitter-nano"
commit = "08a0fbc5fcac4a94fd0e126659300ae9bd4a6700"
